# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshandle',
            name='task_promoter',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4efb\u52a1\u53d1\u8d77\u4eba'),
        ),
    ]
