# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_taskshandle_task_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshandle',
            name='task_cc2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4efb\u52a1\u8f6c\u63a5\u65f6\u6284\u9001\u4eba'),
        ),
    ]
