# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20161103_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshandle',
            name='is_close',
            field=models.BooleanField(default=0),
        ),
    ]
