# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_taskshandle_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshandle',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
