# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_taskshandle_finish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktalk',
            options={'ordering': ['talk_time'], 'verbose_name': '\u8ba8\u8bba\u533a', 'verbose_name_plural': '\u8ba8\u8bba\u533a'},
        ),
        migrations.RemoveField(
            model_name='tasktalk',
            name='task_title',
        ),
        migrations.AddField(
            model_name='tasktalk',
            name='task_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
