# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20161110_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktalk',
            options={'ordering': ['-talk_time'], 'verbose_name': '\u8ba8\u8bba\u533a', 'verbose_name_plural': '\u8ba8\u8bba\u533a'},
        ),
    ]
